FROM jenkins/jenkins:lts-jdk17
USER root

# Install Docker CLI and Node.js/npm
RUN apt-get update && \
    apt-get install -y docker.io curl ca-certificates gnupg && \
    curl -fsSL https://deb.nodesource.com/setup_20.x | bash - && \
    apt-get install -y nodejs && \
    curl -LO "https://dl.k8s.io/release/$(curl -L -s https://dl.k8s.io/release/stable.txt)/bin/linux/amd64/kubectl" && \
    chmod +x kubectl && \
    mv kubectl /usr/local/bin/ && \
    apt-get clean

USER jenkins
