version: '3.8'

services:
  mongodb:
    image: mongo:6.0
    container_name: taskflow-mongodb
    ports:
      - "27017:27017"
    volumes:
      - mongodb_data:/data/db

  auth-service:
    build: ./auth-service
    container_name: taskflow-auth
    ports:
      - "3001:3001"
    environment:
      - MONGO_URI=mongodb://mongodb:27017/taskflow
      - PORT=3001
      - JWT_SECRET=supersecret
    depends_on:
      - mongodb

  team-service:
    build: ./team-service
    container_name: taskflow-team
    ports:
      - "3002:3002"
    environment:
      - MONGO_URI=mongodb://mongodb:27017/taskflow
      - PORT=3002
    depends_on:
      - mongodb

  task-service:
    build: ./task-service
    container_name: taskflow-task
    ports:
      - "3003:3003"
    environment:
      - MONGO_URI=mongodb://mongodb:27017/taskflow
      - PORT=3003
    depends_on:
      - mongodb

  chat-service:
    build: ./chat-service
    container_name: taskflow-chat
    ports:
      - "3004:3004"
    environment:
      - MONGO_URI=mongodb://mongodb:27017/taskflow
      - PORT=3004
    depends_on:
      - mongodb

  frontend:
    build: ./frontend
    container_name: taskflow-frontend
    ports:
      - "80:80"
    depends_on:
      - auth-service
      - team-service
      - task-service
      - chat-service

  jenkins:
    image: jenkins/jenkins:lts
    container_name: taskflow-jenkins
    user: root
    ports:
      - "8080:8080"
      - "50000:50000"
    volumes:
      - jenkins_home:/var/jenkins_home
      - /var/run/docker.sock:/var/run/docker.sock
    restart: unless-stopped

  sonarqube:
    image: sonarqube:community
    container_name: taskflow-sonarqube
    ports:
      - "9000:9000"
    environment:
      - SONAR_ES_BOOTSTRAP_CHECKS_DISABLE=true
      - SONAR_SEARCH_JAVAADDITIONALOPTS=-Des.cluster.routing.allocation.disk.threshold_enabled=false
    volumes:
      - sonarqube_data:/opt/sonarqube/data
      - sonarqube_extensions:/opt/sonarqube/extensions
      - sonarqube_logs:/opt/sonarqube/logs
    restart: unless-stopped

volumes:
  mongodb_data:
  jenkins_home:
  sonarqube_data:
  sonarqube_extensions:
  sonarqube_logs:
