FROM jenkins/jenkins:lts-jdk17
USER root

# Install Docker CLI and Node.js/npm
RUN apt-get update && \
    apt-get install -y docker.io curl ca-certificates gnupg && \
    curl -fsSL https://deb.nodesource.com/setup_20.x | bash - && \
    apt-get install -y nodejs && \
    apt-get clean

USER jenkins
